apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: braviapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: braviapp
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: braviapp
    spec:
      containers:
      - name: braviapp
        image: marcelomata/braviapp:0.0.10
        ports:
        - containerPort: 8090
