apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: antarezapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: antarezapp
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: antarezapp
    spec:
      containers:
      - name: antarezapp
        image: marcelomata/antarezapp:0.0.10
        ports:
        - containerPort: 8090
