apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: antarezdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antarezdb
  template:
    metadata:
      labels:
        app: antarezdb
    spec:
      containers:
      - name: antarezdb
        image: marcelomata/antarezdb:0.0.1
        ports:
        - name: http
          containerPort: 3306
